FROM node:4.8-wheezy

# Install Node.js dependencies
COPY package.json /
RUN npm install

# Copy project files to docker container
COPY views/ /views/
COPY ui.js /

CMD node /ui.js

#
# NOTES
#
# Build this container with (from project root dir):
# docker build -t mike/osv-microservice-demo-ui . -f docker_deploy/Dockerfile-ui
#
# Upload to kubernetes with:
# docker save mike/osv-microservice-demo-ui | docker exec -i kube-node-1 docker load
# docker save mike/osv-microservice-demo-ui | docker exec -i kube-node-2 docker load
#
